# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'VCheckSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

pod 'Alamofire', '~> 5.4.0'
#pod 'AlamofireNetworkActivityLogger', '~> 3.4'
pod 'ARCore/AugmentedFaces', '~> 1.30.0'
pod 'lottie-ios'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end